---
cidr_networks:
  container: 192.168.100.0/24
  tunnel: 192.168.102.0/24
  storage: 192.168.101.0/24

used_ips:
  - "192.168.100.1,192.168.100.20"
  - "192.168.101.1,192.168.101.20"
  - "192.168.102.1,192.168.102.20"


global_overrides:
  internal_lb_vip_address: 192.168.100.11
  external_lb_vip_address: ctrl01.maas
  tunnel_bridge: "br-vxlan"
  management_bridge: "br-mgmt"
  provider_networks:
    - network:
        container_bridge: "br-mgmt"
        container_type: "veth"
        container_interface: "eth1"
        ip_from_q: "container"
        type: "raw"
        group_binds:
          - all_containers
          - hosts
        is_container_address: true
        is_ssh_address: true
    - network:
        container_bridge: "br-vxlan"
        container_type: "veth"
        container_interface: "eth10"
        ip_from_q: "tunnel"
        type: "vxlan"
        range: "1:1000"
        net_name: "vxlan"
        group_binds:
          - neutron_linuxbridge_agent
    - network:
        container_bridge: "br-vlan"
        container_type: "veth"
        container_interface: "eth12"
        host_bind_override: "eth12"
        type: "flat"
        net_name: "flat"
        group_binds:
          - neutron_linuxbridge_agent
    - network:
        container_bridge: "br-vlan"
        container_type: "veth"
        container_interface: "eth11"
        type: "vlan"
        range: "1:1"
        net_name: "vlan"
        group_binds:
          - neutron_linuxbridge_agent
    - network:
        container_bridge: "br-storage"
        container_type: "veth"
        container_interface: "eth2"
        ip_from_q: "storage"
        type: "raw"
        group_binds:
          - glance_api
          - cinder_api
          - cinder_volume
          - nova_compute

###
### Infrastructure
###

# galera, memcache, rabbitmq, utility
shared-infra_hosts:
  ctrl01:
    ip: 192.168.100.11

# repository (apt cache, python packages, etc)
repo-infra_hosts:
  ctrl01:
    ip: 192.168.100.11

# load balancer
haproxy_hosts:
  ctrl01:
    ip: 192.168.100.11

###
### OpenStack
###

# keystone
identity_hosts:
  ctrl01:
    ip: 192.168.100.11

# cinder api services
storage-infra_hosts:
  ctrl01:
    ip: 192.168.100.11

# glance
image_hosts:
  ctrl01:
    ip: 192.168.100.11

# nova api, conductor, etc services
compute-infra_hosts:
  ctrl01:
    ip: 192.168.100.11

# heat
orchestration_hosts:
  ctrl01:
    ip: 192.168.100.11

# horizon
dashboard_hosts:
  ctrl01:
    ip: 192.168.100.11

# neutron server, agents (L3, etc)
network_hosts:
  ctrl01:
    ip: 192.168.100.11

# nova hypervisors
compute_hosts:
  cmp01:
    ip: 192.168.100.12

# cinder storage host (LVM-backed)
storage_hosts:
  cmp01:
    ip: 192.168.100.12
    container_vars:
      cinder_backends:
        limit_container_types: cinder_volume
        lvm:
          volume_group: cinder-volumes
          volume_driver: cinder.volume.drivers.lvm.LVMVolumeDriver
          volume_backend_name: LVM_iSCSI
          iscsi_ip_address: "192.168.101.12"
